version: '1'

services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    command: --wiredTigerCacheSizeGB 1.5 --quiet
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: always
